// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNerbObUdhFIiO0jRRTd2cYhP5AHRH0NQ',
    appId: '1:798245328378:web:425532b11aa319c84ec043',
    messagingSenderId: '798245328378',
    projectId: 'kisaa-9276b',
    authDomain: 'kisaa-9276b.firebaseapp.com',
    databaseURL: 'https://kisaa-9276b-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'kisaa-9276b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_OyyTeLuote2zlS_bLxZiwO4Gab0yKzw',
    appId: '1:798245328378:android:5203a2b45f509ae54ec043',
    messagingSenderId: '798245328378',
    projectId: 'kisaa-9276b',
    databaseURL: 'https://kisaa-9276b-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'kisaa-9276b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4BcgoXaQHIevPyO6gSOxNTF79GtwmzMo',
    appId: '1:798245328378:ios:5b113b4fb78391754ec043',
    messagingSenderId: '798245328378',
    projectId: 'kisaa-9276b',
    databaseURL: 'https://kisaa-9276b-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'kisaa-9276b.appspot.com',
    androidClientId: '798245328378-40ou7uogbm3rosaelkfqde0o252r5at8.apps.googleusercontent.com',
    iosClientId: '798245328378-qevbagpgddff64o2lnj5e2rf0tr8smn5.apps.googleusercontent.com',
    iosBundleId: 'com.example.kisaa23',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4BcgoXaQHIevPyO6gSOxNTF79GtwmzMo',
    appId: '1:798245328378:ios:b590ba53096dfb0e4ec043',
    messagingSenderId: '798245328378',
    projectId: 'kisaa-9276b',
    databaseURL: 'https://kisaa-9276b-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'kisaa-9276b.appspot.com',
    androidClientId: '798245328378-40ou7uogbm3rosaelkfqde0o252r5at8.apps.googleusercontent.com',
    iosClientId: '798245328378-e4aukbi2vtvb8b0eg1jih5n6ntd5j8bh.apps.googleusercontent.com',
    iosBundleId: 'com.example.kisaa23.RunnerTests',
  );
}
